### ISSUE TITLE
Support for 18.04

### ISSUE THREAD

**Issue by srsidd** [stereolabs/zed-docker#10]
I understand this is relatively new, but wondered if there's a plan to support `melodic` and `18.04` docker?

**Comment by adujardin** [comment]
This is already available when using the docker image for the ZED with ROS on Ubuntu 18.04, ROS melodic is used.

It is accessible here : 
- Dockerfile : https://github.com/stereolabs/zed-docker/blob/master/2.8/ubuntu1804/cuda10.0/ros/Dockerfile
- Docker image : `docker pull stereolabs/zed:ubuntu1804-cuda10.0-zed2.8-ros`

**Comment by srsidd** [comment]
Apologies for not being thorough in browsing the repository. Thanks!
