### ISSUE TITLE
Pyzed not installed on latest jetpack images

### ISSUE THREAD

**Issue by rbrigden** [stereolabs/zed-docker#23]
The pyzed package does not appear to be installed in the latest jetson images.  I've verified the following does work for the image tagged `3.1-py-devel-jetson-jp4.2`

```
docker run -it --rm stereolabs/zed:3.2-py-devel-jetson-jp4.4 python3
Python 3.6.9 (default, Apr 18 2020, 01:56:04)                         
[GCC 8.4.0] on linux                                                                   
Type "help", "copyright", "credits" or "license" for more information.   
>>>
>>>
>>> import pyzed.sl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pyzed'
>>> import pyzed.sl
```

**Comment by adujardin** [comment]
Thanks for reporting this issue, indeed there was a missing condition in the python setup script for the JP44. It's now fixed but we forgot to regenerate the docker images. We'll push it asap.
