### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by Zumbalamambo** [stereolabs/zed-docker#29]
It throws the following error,

`Error response from daemon: manifest for stereolabs/zed:3.0-devel-gl-cuda10.2-ubuntu18.04 not found: manifest unknown: manifest unknown
`

**Comment by adujardin** [comment]
The tag is slightly different (see [dockerhub](https://hub.docker.com/layers/stereolabs/zed/3.0-gl-devel-cuda10.2-ubuntu18.04/images/sha256-5566e20cebe377c8234cabdc2867894a8cc72735a31a5ac37a0bf483cdf4af37?context=repo)), it's '`gl-devel`' : 
```
docker pull stereolabs/zed:3.0-gl-devel-cuda10.2-ubuntu18.04
```
