### ISSUE TITLE
Accessing ZED SDK in docker as normal user

### ISSUE THREAD

**Issue by NicoZobernig** [stereolabs/zed-docker#33]
When trying to build the zed2 wrapper for ros2 as non root user inside docker, I am not able to access the ZED libraries in usr/local/zed. After manually setting permissions I was able to build the ros2 wrapper, however i couldnt get it to run:

ros2 launch zed_wrapper zed2.launch.py
[INFO] [launch]: All log files can be found below /home/aegis/.ros/log/2021-03-11-08-58-53-639225-silverXavier-119
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [robot_state_publisher-1]: process started with pid [137]
[INFO] [zed_wrapper-2]: process started with pid [138]
[robot_state_publisher-1] Initialize urdf model from file: /home/aegis/ws/install/zed_wrapper/share/zed_wrapper/urdf/zed2.urdf
[robot_state_publisher-1] Parsing robot urdf xml string.
[robot_state_publisher-1] Link zed2_camera_center had 2 children
[robot_state_publisher-1] Link zed2_left_camera_frame had 1 children
[robot_state_publisher-1] Link zed2_left_camera_optical_frame had 0 children
[robot_state_publisher-1] Link zed2_right_camera_frame had 1 children
[robot_state_publisher-1] Link zed2_right_camera_optical_frame had 0 children
[robot_state_publisher-1] got segment base_link
[robot_state_publisher-1] got segment zed2_camera_center
[robot_state_publisher-1] got segment zed2_left_camera_frame
[robot_state_publisher-1] got segment zed2_left_camera_optical_frame
[robot_state_publisher-1] got segment zed2_right_camera_frame
[robot_state_publisher-1] got segment zed2_right_camera_optical_frame
[zed_wrapper-2] Error: Can't initialize nvrm channel
[zed_wrapper-2] Error: Can't initialize nvrm channel
[zed_wrapper-2] Couldn't create ddkvic Session: Cannot allocate memory
[zed_wrapper-2] nvbuf_utils: Could not create Default NvBufferSession
[ERROR] [zed_wrapper-2]: process has died [pid 138, exit code 255, cmd '/home/aegis/ws/install/zed_wrapper/lib/zed_wrapper/zed_wrapper --ros-args -r __node:=zed_node --params-file /home/aegis/ws/install/zed_wrapper/share/zed_wrapper/config/common.yaml --params-file /home/aegis/ws/install/zed_wrapper/share/zed_wrapper/config/zed2.yaml -r __ns:=/zed2'].
[robot_state_publisher-1] Adding fixed segment from base_link to zed2_camera_center
[robot_state_publisher-1] Adding fixed segment from zed2_camera_center to zed2_left_camera_frame
[robot_state_publisher-1] Adding fixed segment from zed2_left_camera_frame to zed2_left_camera_optical_frame
[robot_state_publisher-1] Adding fixed segment from zed2_camera_center to zed2_right_camera_frame
[robot_state_publisher-1] Adding fixed segment from zed2_right_camera_frame to zed2_right_camera_optical_frame

**Comment by lukazso** [comment]
Also having the same issue.  @NicoZobernig did you find a fix meanwhile?
