### ISSUE TITLE
Feature Request | Add support for JetPack 5.0.2

### ISSUE THREAD

**Issue by nakai-omer** [stereolabs/zed-docker#45]
### Proposal

Nvidia just release JetPack 5.0.2, it will be awesome to have a Zed docker for it.

**Comment by adujardin** [comment]
Hi, 
Sorry I missed your issue, it's actually compatible now with the release of the ZED SDK 3.7.7. https://hub.docker.com/repository/docker/stereolabs/zed

![Screenshot from 2022-09-19 11-15-42](https://user-images.githubusercontent.com/12609780/190986586-8279148d-0a77-4fc4-aef3-0651dc9439c8.png)
